### ISSUE TITLE
Use the ValueType variable to automatically define the ValueData type

### ISSUE THREAD

**Issue by ssokolic** [Crombell95/UserRegistryDSC#2]
## Problem description
When using the module you can define the ValueData. The ValueData is set to int.

If you want to create a STRING for a ValueData entry, you need to change the ValueType in the module.

## Suggestion

Use the ValueType variable to automatically define the ValueData type.

**Comment by Crombell95** [comment]
Thanks for your feedback, appreciate it! Omitting the data type from ValueData and determining based on ValueType afterwards is not possible because it will be cast as object which is not supported. Instead, I have changed the ValueData type to string. This works for both string and int and also solves the issue.
